#pragma once

// This file is generated by the make_handset_header script.

// These are raw audio samples in pcm_u8 format.
// Sample rate: 16000
// Channels: 2

#include "sdkconfig.h"
#if CONFIG_TARGET_PHONE


extern const unsigned char handset_audio_1_samples[];
extern const unsigned int handset_audio_1_samples_len;
extern const unsigned char handset_audio_2_samples[];
extern const unsigned int handset_audio_2_samples_len;
extern const unsigned char handset_audio_3_samples[];
extern const unsigned int handset_audio_3_samples_len;
extern const unsigned char handset_audio_4_samples[];
extern const unsigned int handset_audio_4_samples_len;
extern const unsigned char ring_samples[];
extern const unsigned int ring_samples_len;


#endif
