#pragma once

#include "sdkconfig.h"
#if !CONFIG_TARGET_PHONE


// This file is generated by tools/make_audio_header.

// These are raw audio samples in pcm_u16le format.
// Sample rate: 16000


extern const unsigned char sound_error_samples[];
extern const unsigned int sound_error_samples_len;
extern const unsigned char sound_low_battery_samples[];
extern const unsigned int sound_low_battery_samples_len;
extern const unsigned char sound_success1_samples[];
extern const unsigned int sound_success1_samples_len;
extern const unsigned char sound_success2_samples[];
extern const unsigned int sound_success2_samples_len;
extern const unsigned char sound_success3_samples[];
extern const unsigned int sound_success3_samples_len;
extern const unsigned char sound_tick_samples[];
extern const unsigned int sound_tick_samples_len;
extern const unsigned char sound_tock_samples[];
extern const unsigned int sound_tock_samples_len;


#endif


extern const unsigned char sound_silence_sample[];
extern const unsigned int sound_silence_sample_len;
